version: '2.1'

services:
  local-sqs:
    image: localstack/localstack:1.4.0
    ports:
      - "8010:4566"
    environment:
      - SERVICES=sqs
      - START_WEB=0
  app:
    image: quarkus/amazon-sqs-quickstart
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_SQS_ENDPOINT_OVERRIDE=http://local-sqs:4566
      - QUEUE_URL=${QUEUE_URL}
